### PR TITLE
Native objects and unsubscriptions

### PR DESCRIPTION
**Pull request by akainth015**
* Replaced `d3_map` with the native `Map` class
* Return unsubscribers from listener functions
* Replaced with modern documentation that IDEs can properly parse

### CODE REVIEW

**Comment by akainth015** [comment]
Thanks for the quick feedback! I've reverted the formatting and documentation changes, and I hope it meets your expectations for a quality contribution. Since JavaScript is the only part of this that is documented, would a tool like [documentation.js](https://documentation.js.org/) work to replace Sphinx, which seems like an older tool?

**Comment by auscompgeek** [comment]
This looks good. Given that this drastically changes browser compatibility, I'm hesitant to merge this late in the season, so we might hold off merging this until next year.

We can definitely change what documentation tool we use, but it should be a separate discussion. As you do mention though, using JSDoc comments would help a lot with IDEs.

**Comment by virtuald** [comment]
@amorygalili was discussing moving this project to a more modern Javascript similar to what he's done with the websim... but I think for the sake of backwards compat, we have to wait until this season is done. But I'm not opposed to more modern things as long as they don't make it more difficult to use.

The nice thing about sphinx is that it is what readthedocs supports. I realize this project is a bit different than the other RobotPy projects... but they all use readthedocs. Are there significant advantages to switching?

A quick google search shows a sphinx javascript integration. Not sure how much effort it is to get that to work on RTD, or whether it's even a good idea: https://pypi.org/project/sphinx-js/

**Comment by virtuald** [comment]
Also, currently the sphinx documentation does not get autogenerated from the Javascript code, so the form doesn't matter a whole lot.

**Comment by akainth015** [comment]
@virtuald @auscompgeek I'm going to update this PR so it doesn't use ES6 features, and you can merge it sooner. I'll work on modernizing it in a different branch. I also think it would be prudent to stay away from anything that will require transpiling.

**Comment by amorygalili** [comment]
@akainth015 I've used [sphinx-js](https://pypi.org/project/sphinx-js/) for the [websim documentation](https://robotpy-websim.readthedocs.io/en/latest/tank-drive-model-support.html) you might want to look at. It pulls JSDoc-formatted documentation into readthedocs/rst pages using directives similar to the python autodoc ones. 

@virtuald The project I've been working on is a shuffleboard like interface that sits on top of pynetworktables2js. It makes it easier to create widgets and add them to a dashboard, but I wouldn't call it a replacement to this project.

**Comment by akainth015** [comment]
@auscompgeek I've converted the code to something compatible with older browsers, if you want to take a look at it again.

**Comment by auscompgeek** [comment]
Hmm. @virtuald was there ever an actual reason as to why this was using d3_map instead of a plain object in the first place?

**Comment by akainth015** [comment]
The documented reasoning was to allow "weird" characters in key names, but `Object`s allow anything as keys, even something with spaces, periods, or slashes.

**Comment by auscompgeek** [comment]
So the real reason you'd want to use some sort of Map is either:
- to avoid clashes with already defined properties on the Object prototype (especially `__proto__`), or
- if you want non-string keys (not relevant here since we haven't been using the ES6 Map).

I'm not sure we'd ever end up in a situation where any of our keys collide with predefined names.

**Comment by virtuald** [comment]
My students ran into some issue with normal keys when this was first created, which is why it uses the d3_map.

**Pull request closed without merging**
